### ISSUE TITLE
Release v0.6 

### ISSUE THREAD

**Issue by Affie** [NavAbility/NavAbilitySDK.py#139]
https://github.com/NavAbility/NavAbilitySDK.py/milestone/5
Blocking on docs #124

**Comment by dehann** [comment]
https://pypi.org/project/navabilitysdk/0.6.0/

will do release tag here on github next

**Comment by dehann** [comment]
needed an additional install fix for the sdkCommonGQL submodule files:
- https://github.com/NavAbility/NavAbilitySDK.py/pull/157

See v0.6.0-1, and on PyPi as v0.6.0.post1 (equivalent)
