### ISSUE TITLE
ls and lsf should return empty array if the user, robot, or session is empty.

### ISSUE THREAD

**Issue by GearsAD** [NavAbility/NavAbilitySDK.py#24]
This is currently throwing an error, which isn't correct because the data may still be in queue.

E.g. response:
```
DEBUG:navability.services.variable:Query result: {'USER': [{'name': 'Guest', 'robots': [{'name': 'DemoRobot', 'sessions': []}]}]}
````

**Comment by jim-hill-r** [comment]
@GearsAD I can work this tomorrow if you aren't planning on working it. Just lemme know.

**Comment by GearsAD** [comment]
Thanks, but already prepped the PR :D

**Comment by GearsAD** [comment]
Appreciated though!
