### ISSUE TITLE
addBlob function sdk-py

### ISSUE THREAD

**Issue by GearsAD** [NavAbility/NavAbilitySDK.py#34]
As a user I'd like to be able to add blob data to variables in the graph.

# Technical acceptance
- Build the entities `BlobMetadata` and `BlobData`
- Provide a low-level function that performs the end-to-end upload of a data blob `addDataBlob(BlobMetadata, data:(string or bytes))`
- Provide a low-level function to link this blob to a variable - need a signature for this

**Comment by dehann** [comment]
Did this last week! :-)
