### ISSUE TITLE
Prior factor type is not supported in the SDK

### ISSUE THREAD

**Issue by GearsAD** [NavAbility/NavAbilitySDK.py#43]
As a user I would like to create [Prior](https://github.com/JuliaRobotics/IncrementalInference.jl/blob/master/src/Factors/DefaultPrior.jl#L10-L13). This looks to be the same as [PriorPose2](https://github.com/JuliaRobotics/RoME.jl/blob/master/src/factors/PriorPose2.jl#L13-L15) but @dehann @affie can you confirm that we can simply copy PriorPose2 as Prior?

**Comment by dehann** [comment]
I think you can copy yes, for many actually .  We've been trying to make factors more the same with only field .Z for all the common ones.

**Comment by GearsAD** [comment]
Followup in IIF: https://github.com/JuliaRobotics/IncrementalInference.jl/issues/1500
