### ISSUE TITLE
Dont think Pose2Point2BearingRange is done yet?

### ISSUE THREAD

**Issue by dehann** [NavAbility/NavAbilitySDK.py#64]
Hi @GearsAD , you might know best.  Does Pose2Point2BearingRange exist in this SDK.py yet? I searched for it in the code but did not see it.

**Comment by GearsAD** [comment]
It's there: https://github.com/NavAbility/NavAbilitySDK.py/blob/main/src/navability/entities/factor/inferencetypes.py#L209

I'll look quick.

**Comment by dehann** [comment]
ah, thats where it is, thanks.  I had some trouble but did't try very hard in Tut1, BearingRange factors to l1 is the last thing to do in the SDK.py version.  Let me know what you find, I'm on the SDK.jl async stuff for now, will be back on this later.

**Comment by GearsAD** [comment]
I just tagged it although I don't think that's the problem. I'm rebuilding the notebook right now.

**Comment by dehann** [comment]
Cool, just make sure you have the latest from main branch.  I pushed the last fixes around 20 mins ago

**Comment by GearsAD** [comment]
Just tested and uncommented the code for those elements and they work - https://github.com/NavAbility/BinderNotebooks/pull/53. The tutorial needs work but the factors exist.

**Comment by dehann** [comment]
few silly fixes were still needed in Tut1 SDK.py version, but thats all PR'ed and should be ready.
