### ISSUE TITLE
Update SDK.py multihypo

### ISSUE THREAD

**Issue by dehann** [NavAbility/NavAbilitySDK.py#66]
(converted to issue, someone mentioned this:)

int -> float
I didn't have time to figure python sdk out to see what else is needed.

**Comment by dehann** [comment]
Float best place to start, also see
- https://github.com/NavAbility/NavAbilitySDK.jl/issues/97

**Comment by Affie** [comment]
This is not working in binder yet. I don't know of a way to test it other than to release a new version and update binder to the new version. @GearsAD, can you help with this please?

**Comment by dehann** [comment]
I think Johan means 
- we need to release a new patch release for SDK.py
- Then also update the workspace for Binder to get the new SDK package release

**Comment by dehann** [comment]
Hi @GearsAD assigning your way, sounds like this is blocking on new SDK.py patch release.
